name = "analysis"
version = "0.1.0"
defaultTargets = ["Analysis"]

[[lean_lib]]
name = "Analysis"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "main"
