name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
      - name: build output
        run: |
          lake exe analysis-book
      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_out/html-multi'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
