name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        working-directory: ./analysis-book
      - name: build output
        working-directory: ./analysis-book
        run: |
          lake exe analysis-book
      - name: build docs
        working-directory: ./analysis
        run: |
          lake exe Analysis:docs
      - name: Copy docs to analysis-book
        working-directory: ./analysis-book
        run: |
          cp -r ../.lake/build/doc _site/docs
      - name: Upload website
        working-directory: ./analysis-book
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        working-directory: ./analysis-book
        id: deployment
        uses: actions/deploy-pages@v4
